"""Source and API details"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = ['cdp_search', 'cdp_conninfo', 'CDP', 'CDPMethod', 'CDPDomain', 'PageDomain', 'Page', 'AXNode', 'AXTree',
           'build_ax_tree', 'cdp_yolo']

# %% ../nbs/00_core.ipynb #34dc06ce
from fastcore.utils import *
import websockets, json, platform, asyncio, inspect, base64, httpx
from contextlib import asynccontextmanager

# %% ../nbs/00_core.ipynb #930c2391
if '__file__' not in globals():
    _root = Path.cwd()
    if not (Path.cwd()/'pyproject.toml').exists(): _root = _root.parent
    __file__ = _root/'fastcdp'/'core.py'

_path = Path(__file__).parent
_bp = (_path/'browser_protocol.json').read_json()
_jp = (_path/'js_protocol.json').read_json()
_cdp_domains = _bp['domains'] + _jp['domains']

# %% ../nbs/00_core.ipynb #12182cb2
def cdp_search(q:str):
    "Search CDP domains and commands by name or description"
    q = q.lower()
    res = []
    for d in _cdp_domains:
        for cmd in d.get('commands', []):
            desc = cmd.get('description', '')
            if q in cmd['name'].lower() or q in desc.lower():
                res.append(f"{d['domain']}.{cmd['name']}: {desc[:120]}")
        for evt in d.get('events', []):
            desc = evt.get('description', '')
            if q in evt['name'].lower() or q in desc.lower():
                res.append(f"  evt {d['domain']}.{evt['name']}: {desc[:120]}")
    return '\n'.join(res)

# %% ../nbs/00_core.ipynb #65ed8e9a
def _lower1(s): return s[0].lower() + s[1:]
def _upper1(s): return s[0].upper() + s[1:]

_chrome_paths = dict(
    Darwin='Library/Application Support/Google/Chrome/DevToolsActivePort',
    Linux ='.config/google-chrome/DevToolsActivePort')

def cdp_conninfo(p=None):
    if not p: p = (Path.home()/(_chrome_paths.get(platform.system()) or _chrome_paths['Linux'])).read_text()
    lines = p.strip().split('\n')
    return ''.join(lines[:2])

# %% ../nbs/00_core.ipynb #48f443ee
class CDP:
    "Chrome DevTools Protocol connection with event support"
    def __init__(self, wsconn=None, debug=False):
        self._id,self._pending,self._events = 0,{},{}
        store_attr()

    @classmethod
    async def connect(cls, p=None, wsconn=None, debug=None):
        if wsconn is None: wsconn = cdp_conninfo()
        self = cls(wsconn, debug=debug)
        url = self.wsconn if self.wsconn.startswith('ws') else f'ws://127.0.0.1:{self.wsconn}'
        self.ws = await websockets.connect(url)
        self._reader = asyncio.create_task(self._read_loop())
        self._keep = asyncio.create_task(self._keepalive())
        return self

    async def _read_loop(self):
        try:
            async for raw in self.ws:
                msg = json.loads(raw)
                if 'id' in msg:
                    if (fut := self._pending.pop(msg['id'], None)): fut.set_result(msg)
                elif 'method' in msg:
                    if self.debug: print(f"EVT: {msg['method']} sid={msg.get('sessionId','')[:8]}")
                    for q in self._events.get(msg['method'], []): q.put_nowait(msg)
        except websockets.ConnectionClosed: pass

    async def _keepalive(self):
        while True:
            try: await self('Runtime.evaluate', expression='1')
            except: break
            await asyncio.sleep(30)

    async def __call__(self, method, sid=None, **params):
        self._id += 1
        msg = dict(id=self._id, method=method)
        if params: msg['params'] = params
        if sid: msg['sessionId'] = sid
        fut = asyncio.get_event_loop().create_future()
        self._pending[self._id] = fut
        await self.ws.send(json.dumps(msg))
        r = await fut
        if 'error' in r: raise RuntimeError(f"{method}: {r['error']}")
        res = r.get('result', {})
        return first(res.values()) if len(res) == 1 else res

    async def close(self):
        self._keep.cancel()
        self._reader.cancel()
        await self.ws.close()

    @property
    def is_open(self): return self.ws.state.name == 'OPEN'

    def __dir__(self): return super().__dir__() + [_lower1(o) for o in _domains.keys()]

    def __getattr__(self, domain):
        if domain.startswith('_'): raise AttributeError()
        return CDPDomain(self, _upper1(domain))

# %% ../nbs/00_core.ipynb #1e09344e
@patch(cls_method=True)
async def remote(cls:CDP, port=9222, debug=None):
    "Connect via Chrome remote debugging HTTP endpoint"
    async with httpx.AsyncClient() as client:
        url = (await client.get(f'http://localhost:{port}/json/version')).json()['webSocketDebuggerUrl']
    return await cls.connect(wsconn=url, debug=debug)

# %% ../nbs/00_core.ipynb #e7db5a91
@patch(as_prop=True)
async def pages(self:CDP):
    return [t for t in (await self('Target.getTargets')) if t['type'] == 'page']

# %% ../nbs/00_core.ipynb #7b94f2b8
_domains = {d['domain']: d for d in _cdp_domains}

def _find_cmd(domain, method):
    d = _domains.get(domain, {})
    return first(c for c in d.get('commands', []) if c['name'] == method)

def _cmd_sig(cmd):
    _P = inspect.Parameter
    ps = [_P(p['name'], _P.KEYWORD_ONLY, default=None if p.get('optional') else _P.empty) for p in cmd.get('parameters', [])]
    return inspect.Signature([_P('sid', _P.KEYWORD_ONLY, default=None)] + ps)

def _cmd_doc(domain, method, cmd):
    doc = f"{domain}.{method}"
    if cmd.get('description'): doc += f" - {cmd['description']}"
    for p in cmd.get('parameters', []):
        opt = ' (optional)' if p.get('optional') else ''
        doc += f"\n  {p['name']}{opt}: {p.get('description', '')}"
    return doc

# %% ../nbs/00_core.ipynb #1c2d0198
class CDPMethod:
    def __init__(self, cdp, domain, method):
        store_attr()
        if (cmd := _find_cmd(domain, method)):
            self.__doc__ = _cmd_doc(domain, method, cmd)
            self.__signature__ = _cmd_sig(cmd)

    async def __call__(self, sid=None, **kw): return await self.cdp(f'{self.domain}.{self.method}', sid=sid, **kw)

class CDPDomain:
    def __init__(self, cdp, domain): store_attr()

    def __getattr__(self, method):
        if method.startswith('_'): raise AttributeError()
        return CDPMethod(self.cdp, self.domain, method)

    def __dir__(self):
        d = _domains.get(self.domain, {})
        return [c['name'] for c in d.get('commands', [])] + [e['name'] for e in d.get('events', [])]

# %% ../nbs/00_core.ipynb #3c348501
@patch
async def attach(self:CDP, tid):
    return await self.target.attachToTarget(targetId=tid, flatten=True)

@patch
async def eval(self:CDP, expr, sid=None):
    return (await self.runtime.evaluate(sid=sid, expression=expr)).get('value')

# %% ../nbs/00_core.ipynb #5b1d1bb4
@patch
@asynccontextmanager
async def on(self:CDP, event):
    q = asyncio.Queue()
    self._events.setdefault(event, []).append(q)
    try: yield q
    finally: self._events[event].remove(q)

@patch
async def wait_event(self:CDP, event, timeout=10):
    async with self.on(event) as q:
        return await asyncio.wait_for(q.get(), timeout)


# %% ../nbs/00_core.ipynb #1d2f0ec0
@patch
async def wait_load(self:CDP, sid=None, timeout=10):
    while True:
        e = await self.wait_event('Page.lifecycleEvent', timeout=timeout)
        print(e)
        if e['params'].get('name') == 'networkIdle': return

@patch
async def wait_for(self:CDP, expr, sid=None, timeout=10):
    "Wait for JS expression to be truthy, return its value"
    deadline = asyncio.get_event_loop().time() + timeout
    while asyncio.get_event_loop().time() < deadline:
        r = await self.eval(expr, sid)
        if r: return r
        await asyncio.sleep(0.05)
    raise TimeoutError(f'Timed out waiting for: {expr}')

@patch
async def wait_for_selector(self:CDP, sel, sid=None, timeout=10):
    "Wait for CSS selector to match an element"
    return await self.wait_for(f'!!document.querySelector("{sel}")', sid, timeout)

# %% ../nbs/00_core.ipynb #e9e3f54d
def _copy_meta(src, dest):
    if hasattr(src, '__doc__'): dest.__doc__ = src.__doc__
    if hasattr(src, '__signature__'):
        dest.__signature__ = src.__signature__.replace(
            parameters=[p for p in src.__signature__.parameters.values() if p.name != 'sid'])
    return dest

# %% ../nbs/00_core.ipynb #1d63dba1
class PageDomain:
    def __init__(self, sid, domain): store_attr()
    def __dir__(self): return self.domain.__dir__()

    def __getattr__(self, name):
        if name.startswith('_'): raise AttributeError(name)
        m = getattr(self.domain, name)
        async def _f(**kw): return await m(sid=self.sid, **kw)
        return _copy_meta(m, _f)

# %% ../nbs/00_core.ipynb #8fb12710
class Page:
    def __init__(self, cdp, t, sid, owned=False): store_attr()

    @classmethod
    async def new(cls, t=None, cdp=None, **kwargs):
        if not cdp: cdp,owned = await CDP.connect(**kwargs),True
        else: owned = False
        if not t: t = await cdp.target.createTarget(url='about:blank')
        sid = await cdp.attach(t)
        self = cls(cdp, t, sid, owned=owned)
        await cdp.page.enable(sid=sid)
        return self

    def __getattr__(self, name):
        if name.startswith('_'): raise AttributeError(name)
        o = getattr(self.cdp, name)
        if isinstance(o, CDPDomain): return PageDomain(self.sid, o)
        if not callable(o): return o
        async def _f(*a, **kw): return await o(*a, sid=self.sid, **kw)
        return _copy_meta(o, _f)

    async def close(self):
        # Ignore errors if already closed
        try: await self.cdp.target.closeTarget(targetId=self.t)
        except RuntimeError: pass
        if self.owned: await self.cdp.close()

    @property
    def is_open(self): return self.cdp.is_open

    def __dir__(self): return self.cdp.__dir__()

# %% ../nbs/00_core.ipynb #bf90b19e
@patch
async def active_page(self:CDP):
    for t in (await self('Target.getTargets')):
        if t['type'] != 'page': continue
        sid = await self.attach(t['targetId'])
        if await self.eval('document.hasFocus()', sid): return t, sid
        await self.target.detachFromTarget(sessionId=sid)

@patch(cls_method=True)
async def remote_page(cls:CDP, port=9222, debug=None):
    "Connect via remote debugging and return Page for the active tab"
    cdp = await cls.remote(port=port, debug=debug)
    result = await cdp.active_page()
    if not result: raise RuntimeError("No focused page found")
    t, sid = result
    return Page(cdp, t['targetId'], sid, owned=True)


# %% ../nbs/00_core.ipynb #3d0570b5
@patch
async def new_page(self:CDP):
    "Create a new tab, return Page"
    t = await self.target.createTarget(url='about:blank')
    await asyncio.sleep(0.1)
    return await Page.new(t, self)

# %% ../nbs/00_core.ipynb #0bf3d185
@patch
async def wait_for_ready(self:CDP, sid=None, timeout=10, idle_ms=500):
    "Wait until network is idle for idle_ms"
    await self.network.enable(sid=sid)
    deadline = asyncio.get_event_loop().time() + timeout
    while asyncio.get_event_loop().time() < deadline:
        async with self.on('Network.requestWillBeSent') as q:
            try: await asyncio.wait_for(q.get(), timeout=idle_ms/1000)
            except asyncio.TimeoutError: return
    raise TimeoutError('Timed out waiting for network idle')


@patch
@asynccontextmanager
async def wait_ready(self:CDP, sid=None, timeout=10, idle_ms=500):
    "Context manager: subscribes before action, waits for load+idle after"
    await self.page.setLifecycleEventsEnabled(sid=sid, enabled=True)
    async with self.on('Page.loadEventFired') as q_load:
        yield
        await asyncio.wait_for(q_load.get(), timeout=timeout)
        await self.wait_for_ready(sid=sid, timeout=timeout, idle_ms=idle_ms)

@patch
async def goto(self:CDP, url, sid=None, **kwargs):
    "Navigate to url and wait for load+idle"
    async with self.wait_ready(sid=sid, **kwargs): await self.page.navigate(sid=sid, url=url)

# %% ../nbs/00_core.ipynb #2cea0ba8
@patch
async def screenshot(self:CDP, sid=None):
    from IPython.display import Image
    b64 = await self.page.captureScreenshot(sid=sid, format='png')
    return Image(base64.b64decode(b64))

# %% ../nbs/00_core.ipynb #786aa6ef
class AXNode:
    "Chrome accessibility tree node with compact repr"
    def __init__(self, raw):
        self.role = nested_idx(raw, 'role', 'value') or ''
        self.name = nested_idx(raw, 'name', 'value') or ''
        self.props = {p['name']: nested_idx(p, 'value', 'value') for p in raw.get('properties', [])}
        self.children = []
        self.node_id = raw.get('nodeId')
        self.backend_id = raw.get('backendDOMNodeId')
        self.ignored = raw.get('ignored', False)
        self._raw = raw

    def _repr_markdown_(self, depth=0):
        pre = '  ' * depth
        ps = ''.join(f' `{k}={v}`' for k,v in self.props.items() if v not in (False, None, '', 'false'))
        bid = f' [#{self.backend_id}]' if self.backend_id else ''
        line = f'{pre}- **{self.role}** "{self.name}"{ps}{bid}'
        return '\n'.join([line] + [c._repr_markdown_(depth+1) for c in self.children])

    __str__ = __repr__ = _repr_markdown_

class AXTree(AXNode):
    def _repr_markdown_(self): return f'<div class="prose">\n\n{super()._repr_markdown_(0)}\n\n</div>'

# %% ../nbs/00_core.ipynb #ce180f22
def _simplify(node):
    node.children = [n for c in node.children for n in _simplify(c)]
    if node.role in ('none', 'generic', 'paragraph') and not node.name:
        if not node.children: return []
        return node.children  # splice children up
    return [node]

def build_ax_tree(nodes):
    "Build AXNode tree from flat CDP accessibility node list"
    by_id = {}
    for raw in nodes:
        n = AXNode(raw)
        by_id[n.node_id] = n
    for raw in nodes:
        parent = by_id.get(raw.get('nodeId'))
        for cid in raw.get('childIds', []):
            if (child := by_id.get(cid)): parent.children.append(child)
    if not nodes: return
    root = by_id.get(nodes[0]['nodeId'])
    if not (result := _simplify(root)): return None
    result = result[0]
    result.__class__ = AXTree
    return result

# %% ../nbs/00_core.ipynb #2a418b3b
@patch
async def ax_tree(self:CDP, sid=None):
    "Get accessibility tree for session"
    await self.accessibility.enable(sid=sid)
    return build_ax_tree(await self.accessibility.getFullAXTree(sid=sid))

# %% ../nbs/00_core.ipynb #92b49b0c
@patch
def find(self:AXNode, role=None, name=None):
    "Find first descendant matching role and/or name substring"
    if (not role or role == self.role) and (not name or name in self.name): return self
    for c in self.children:
        if (r := c.find(role, name)): return r

@patch
def find_id(self:AXNode, role=None, name=None):
    "Find first descendant matching role and/or name substring"
    res = self.find(role, name)
    return res.backend_id if res else None

@patch
def find_all(self:AXNode, role=None, name=None):
    "Find all descendants matching role and/or name substring"
    res = []
    if (not role or role == self.role) and (not name or name in self.name): res.append(self)
    for c in self.children: res += c.find_all(role, name)
    return res

# %% ../nbs/00_core.ipynb #6639fea3
@patch
async def js_node(self:CDP, fn, backendNodeId, sid=None):
    obj = await self.DOM.resolveNode(sid=sid, backendNodeId=backendNodeId)
    return await self.runtime.callFunctionOn(sid=sid, functionDeclaration=fn,
                                              objectId=obj['objectId'])

@patch
async def js_node_run(self:CDP, code, backendNodeId, sid=None):
    return await self.js_node(f'function() {{ {code} }}', backendNodeId, sid=sid)

@patch
async def click(self:CDP, backendNodeId, sid=None):
    await self.js_node_run('this.click()', backendNodeId, sid=sid)

# %% ../nbs/00_core.ipynb #f512a6f2
@patch
async def fill_text(self:CDP, backendNodeId, text, sid=None):
    await self.DOM.focus(sid=sid, backendNodeId=backendNodeId)
    await self.input.insertText(sid=sid, text=text)

# %% ../nbs/00_core.ipynb #99fda301
@patch
async def click_and_wait(self:CDP, backendNodeId, sid=None, **kwargs):
    "Click element and wait for load+idle"
    async with self.wait_ready(sid=sid, **kwargs): await self.js_node_run('this.click()', backendNodeId, sid=sid)

# %% ../nbs/00_core.ipynb #904883ee
def cdp_yolo():
    "Allow all CDP classes in safepyrun"
    from pyskills import allow
    allow({CDP:..., CDPDomain:..., CDPMethod:...})
    allow({PageDomain:..., Page:..., AXNode:..., AXTree:...})
