"""Source and API details"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = ['cdp_domains', 'cdp_search', 'CDP', 'CDPMethod', 'CDPDomain', 'PageDomain', 'Page', 'cdp_yolo', 'Event']

# %% ../nbs/00_core.ipynb #34dc06ce
from fastcore.utils import *
import websockets, json, platform, asyncio, inspect, base64

# %% ../nbs/00_core.ipynb #c141286b
_path = Path(__file__).parent

_bp = (_path/'browser_protocol.json').read_json()
_jp = (_path/'js_protocol.json').read_json()

cdp_domains = _bp['domains'] + _jp['domains']

# %% ../nbs/00_core.ipynb #12182cb2
def cdp_search(q:str):
    "Search CDP domains and commands by name or description"
    q = q.lower()
    res = []
    for d in cdp_domains:
        for cmd in d.get('commands', []):
            desc = cmd.get('description', '')
            if q in cmd['name'].lower() or q in desc.lower():
                res.append(f"{d['domain']}.{cmd['name']}: {desc[:120]}")
        for evt in d.get('events', []):
            desc = evt.get('description', '')
            if q in evt['name'].lower() or q in desc.lower():
                res.append(f"  evt {d['domain']}.{evt['name']}: {desc[:120]}")
    return '\n'.join(res)

# %% ../nbs/00_core.ipynb #65ed8e9a
def _lower1(s): return s[0].lower() + s[1:]
def _upper1(s): return s[0].upper() + s[1:]

_chrome_paths = dict(
    Darwin='Library/Application Support/Google/Chrome/DevToolsActivePort',
    Linux ='.config/google-chrome/DevToolsActivePort')

# %% ../nbs/00_core.ipynb #48f443ee
class CDP:
    "Chrome DevTools Protocol connection with event support"
    def __init__(self, port=9222, debug=False):
        self._id,self._pending,self._events = 0,{},{}
        store_attr()

    @classmethod
    async def connect(cls, port=9222):
        self = cls(port=port)
        p = Path.home()/(_chrome_paths.get(platform.system()) or _chrome_paths['Linux'])
        lines = p.read_text().strip().split('\n')
        self.ws = await websockets.connect(f'ws://127.0.0.1:{lines[0]}{lines[1]}')
        self._reader = asyncio.create_task(self._read_loop())
        self._keep = asyncio.create_task(self._keepalive())
        return self

    async def _read_loop(self):
        try:
            async for raw in self.ws:
                msg = json.loads(raw)
                if 'id' in msg:
                    if (fut := self._pending.pop(msg['id'], None)): fut.set_result(msg)
                elif 'method' in msg:
                    if self.debug: print(f"EVT: {msg['method']} sid={msg.get('sessionId','')[:8]}")
                    for q in self._events.get(msg['method'], []): q.put_nowait(msg)
        except websockets.ConnectionClosed: pass

    async def _keepalive(self):
        while True:
            try: await self('Runtime.evaluate', expression='1')
            except: break
            await asyncio.sleep(30)

    async def __call__(self, method, sid=None, **params):
        self._id += 1
        msg = dict(id=self._id, method=method)
        if params: msg['params'] = params
        if sid: msg['sessionId'] = sid
        fut = asyncio.get_event_loop().create_future()
        self._pending[self._id] = fut
        await self.ws.send(json.dumps(msg))
        r = await fut
        if 'error' in r: raise RuntimeError(f"{method}: {r['error']}")
        res = r.get('result', {})
        return first(res.values()) if len(res) == 1 else res

    async def close(self):
        self._keep.cancel()
        self._reader.cancel()
        await self.ws.close()

    def __dir__(self): return super().__dir__() + [_lower1(o) for o in _domains.keys()]

    def __getattr__(self, domain):
        if domain.startswith('_'): raise AttributeError()
        return CDPDomain(self, _upper1(domain))

# %% ../nbs/00_core.ipynb #e7db5a91
@patch(as_prop=True)
async def pages(self:CDP):
    return [t for t in (await self('Target.getTargets')) if t['type'] == 'page']

# %% ../nbs/00_core.ipynb #7b94f2b8
_domains = {d['domain']: d for d in cdp_domains}

def _find_cmd(domain, method):
    d = _domains.get(domain, {})
    return first(c for c in d.get('commands', []) if c['name'] == method)

def _cmd_sig(cmd):
    _P = inspect.Parameter
    ps = [_P(p['name'], _P.KEYWORD_ONLY, default=None if p.get('optional') else _P.empty) for p in cmd.get('parameters', [])]
    return inspect.Signature([_P('sid', _P.KEYWORD_ONLY, default=None)] + ps)

def _cmd_doc(domain, method, cmd):
    doc = f"{domain}.{method}"
    if cmd.get('description'): doc += f" - {cmd['description']}"
    for p in cmd.get('parameters', []):
        opt = ' (optional)' if p.get('optional') else ''
        doc += f"\n  {p['name']}{opt}: {p.get('description', '')}"
    return doc

# %% ../nbs/00_core.ipynb #1c2d0198
class CDPMethod:
    def __init__(self, cdp, domain, method):
        store_attr()
        if (cmd := _find_cmd(domain, method)):
            self.__doc__ = _cmd_doc(domain, method, cmd)
            self.__signature__ = _cmd_sig(cmd)

    async def __call__(self, sid=None, **kw): return await self.cdp(f'{self.domain}.{self.method}', sid=sid, **kw)

class CDPDomain:
    def __init__(self, cdp, domain): store_attr()

    def __getattr__(self, method):
        if method.startswith('_'): raise AttributeError()
        return CDPMethod(self.cdp, self.domain, method)

    def __dir__(self):
        d = _domains.get(self.domain, {})
        return [c['name'] for c in d.get('commands', [])] + [e['name'] for e in d.get('events', [])]

# %% ../nbs/00_core.ipynb #3c348501
@patch
async def attach(self:CDP, tid):
    return await self.target.attachToTarget(targetId=tid, flatten=True)

@patch
async def eval(self:CDP, expr, sid=None):
    return (await self.runtime.evaluate(sid=sid, expression=expr)).get('value')

# %% ../nbs/00_core.ipynb #b8a57cf7
@patch
def on(self:CDP, event):
    q = asyncio.Queue()
    self._events.setdefault(event, []).append(q)
    return q

@patch
async def wait_event(self:CDP, event, timeout=10):
    q = self.on(event)
    try: return await asyncio.wait_for(q.get(), timeout)
    finally: self._events[event].remove(q)

# %% ../nbs/00_core.ipynb #1d2f0ec0
@patch
async def wait_load(self:CDP, sid=None, timeout=10):
    while True:
        e = await self.wait_event('Page.lifecycleEvent', timeout=timeout)
        print(e)
        if e['params'].get('name') == 'networkIdle': return

@patch
async def wait_for(self:CDP, expr, sid=None, timeout=10):
    "Wait for JS expression to be truthy, return its value"
    deadline = asyncio.get_event_loop().time() + timeout
    while asyncio.get_event_loop().time() < deadline:
        r = await self.eval(expr, sid)
        if r: return r
        await asyncio.sleep(0.05)
    raise TimeoutError(f'Timed out waiting for: {expr}')

@patch
async def wait_for_selector(self:CDP, sel, sid=None, timeout=10):
    "Wait for CSS selector to match an element"
    return await self.wait_for(f'!!document.querySelector("{sel}")', sid, timeout)

# %% ../nbs/00_core.ipynb #8d61d10b
class PageDomain:
    def __init__(self, sid, domain): store_attr()

    def __getattr__(self, name):
        if name.startswith('_'): raise AttributeError(name)
        m = getattr(self.domain, name)
        async def _f(**kw): return await m(sid=self.sid, **kw)
        return _f

class Page:
    def __init__(self, cdp, t, sid): store_attr()

    @classmethod
    async def new(cls, cdp, t):
        sid = await cdp.attach(t)
        self = cls(cdp, t, sid)
        await cdp.page.enable(sid=sid)
        return self

    def __getattr__(self, name):
        if name.startswith('_'): raise AttributeError(name)
        o = getattr(self.cdp, name)
        if isinstance(o, CDPDomain): return PageDomain(self.sid, o)
        if not callable(o): return o
        async def _f(*a, **kw): return await o(*a, sid=self.sid, **kw)
        return _f

    async def close(self): return await self.cdp.target.closeTarget(targetId=self.t)

# %% ../nbs/00_core.ipynb #3d0570b5
@patch
async def new_page(self:CDP):
    "Create a new tab, return Page"
    t = await self.target.createTarget(url='about:blank')
    return await Page.new(self, t)

# %% ../nbs/00_core.ipynb #31129bec
def cdp_yolo():
    "Allow all CDP classes in safepyrun"
    allow({CDP:..., CDPDomain:..., CDPMethod:...})
    allow({PageDomain:..., Page:...})

# %% ../nbs/00_core.ipynb #1066efb4
class Event:
    "Context manager for CDP event subscription"
    def __init__(self, cdp, name): store_attr()
    async def __aenter__(self):
        self.q = self.cdp.on(self.name)
        return self.q
    async def __aexit__(self, *args): self.cdp._events[self.name].remove(self.q)

@patch
def event(self:CDP, name): return Event(self, name)

# %% ../nbs/00_core.ipynb #c034fee5
@patch
async def goto(self:CDP, url, sid=None, timeout=10):
    async with self.event('Page.loadEventFired') as q:
        await self.page.navigate(sid=sid, url=url)
        await asyncio.wait_for(q.get(), timeout=timeout)
    await self.wait_for_selector('body', sid)

# %% ../nbs/00_core.ipynb #2cea0ba8
@patch
async def screenshot(self:CDP, sid=None):
    from IPython.display import Image
    b64 = await self.page.captureScreenshot(sid=sid, format='png')
    return Image(base64.b64decode(b64))
