"""Source and API details

Docs: https://AnswerDotAI.github.io/fastcdp/core.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = ['cdp_search', 'cdp_conninfo', 'CDP', 'chrome_bin', 'Targets', 'CDPMethod', 'CDPDomain', 'PageDomain', 'Page', 'AXNode',
           'AXTree', 'build_ax_tree', 'cdp_yolo']

# %% ../nbs/00_core.ipynb #34dc06ce
from fastcore.utils import *
from fastcore.net import is_port_free, wait_port_free_async
import shutil, websockets, json, platform, asyncio, inspect, base64, httpx
from contextlib import asynccontextmanager

# %% ../nbs/00_core.ipynb #930c2391
if '__file__' not in globals():
    _root = Path.cwd()
    if not (Path.cwd()/'pyproject.toml').exists(): _root = _root.parent
    __file__ = _root/'fastcdp'/'core.py'

_path = Path(__file__).parent
_bp = (_path/'browser_protocol.json').read_json()
_jp = (_path/'js_protocol.json').read_json()
_cdp_domains = _bp['domains'] + _jp['domains']

# %% ../nbs/00_core.ipynb #12182cb2
def cdp_search(q:str):
    "Search CDP domains and commands by name or description"
    q = q.lower()
    res = []
    for d in _cdp_domains:
        for cmd in d.get('commands', []):
            desc = cmd.get('description', '')
            if q in cmd['name'].lower() or q in desc.lower():
                res.append(f"{d['domain']}.{cmd['name']}: {desc[:120]}")
        for evt in d.get('events', []):
            desc = evt.get('description', '')
            if q in evt['name'].lower() or q in desc.lower():
                res.append(f"  evt {d['domain']}.{evt['name']}: {desc[:120]}")
    return '\n'.join(res)

# %% ../nbs/00_core.ipynb #65ed8e9a
def _lower1(s): return s[0].lower() + s[1:]
def _upper1(s): return s[0].upper() + s[1:]

_chrome_paths = dict(
    Darwin=['Library/Application Support/Google/Chrome/DevToolsActivePort',
            'Library/Application Support/Chromium/DevToolsActivePort'],
    Linux=['.config/google-chrome/DevToolsActivePort',
           '.config/chromium/DevToolsActivePort'])

def cdp_conninfo(p:str=None, d:str|Path=None):
    "Connection info from contents `p`, profile dir `d`, or the default Chrome profile"
    if d: p = (Path(d)/'DevToolsActivePort').read_text()
    if not p:
        paths = _chrome_paths.get(platform.system(), _chrome_paths['Linux'])
        f = first(Path.home()/p for p in paths if (Path.home()/p).exists())
        if not f: raise FileNotFoundError('No Chrome or Chromium DevToolsActivePort found')
        p = f.read_text()
    lines = p.strip().split('\n')
    return ''.join(lines[:2])

# %% ../nbs/00_core.ipynb #48f443ee
class CDP:
    "Chrome DevTools Protocol connection with event support"
    def __init__(self, wsconn:str=None, debug:bool=False):
        self._id,self._pending,self._events = 0,{},{}
        store_attr()

    @classmethod
    async def connect(cls, p:str=None, wsconn:str=None, debug:bool=None):
        if wsconn is None: wsconn = cdp_conninfo()
        self = cls(wsconn, debug=debug)
        url = self.wsconn if self.wsconn.startswith('ws') else f'ws://127.0.0.1:{self.wsconn}'
        self.ws = await websockets.connect(url)
        self._reader = asyncio.create_task(self._read_loop())
        self._keep = asyncio.create_task(self._keepalive())
        return self

    async def _read_loop(self):
        try:
            async for raw in self.ws:
                msg = json.loads(raw)
                if 'id' in msg:
                    if (fut := self._pending.pop(msg['id'], None)): fut.set_result(msg)
                else: self._dispatch(msg)
        except websockets.ConnectionClosed: pass

    def _dispatch(self, msg):
        "Route an event frame to every queue subscribed to its method"
        if 'method' not in msg: return
        if self.debug: print(f"EVT: {msg['method']} sid={msg.get('sessionId','')[:8]}")
        for q in self._events.get(msg['method'], []): q.put_nowait(msg)

    async def _keepalive(self):
        while True:
            try: await self('Runtime.evaluate', expression='1')
            except: break
            await asyncio.sleep(30)

    async def _send(self, msg):
        "Send one command frame and return its reply frame; transports override this"
        self._id += 1
        msg['id'] = self._id
        fut = asyncio.get_event_loop().create_future()
        self._pending[self._id] = fut
        await self.ws.send(json.dumps(msg))
        return await fut

    async def __call__(self, method:str, sid:str=None, **params):
        msg = dict(method=method)
        if params: msg['params'] = params
        if sid: msg['sessionId'] = sid
        r = await self._send(msg)
        if 'error' in r: raise RuntimeError(f"{method}: {r['error']}")
        res = r.get('result', {})
        return first(res.values()) if len(res) == 1 else res

    async def close(self):
        self._keep.cancel()
        self._reader.cancel()
        if (t := getattr(self, '_dialog_task', None)): t.cancel()
        await self.ws.close()

    @property
    def is_open(self): return self.ws.state.name == 'OPEN'

    def __dir__(self): return super().__dir__() + [_lower1(o) for o in _domains.keys()]

    def __getattr__(self, domain):
        if domain.startswith('_'): raise AttributeError()
        return CDPDomain(self, _upper1(domain))

# %% ../nbs/00_core.ipynb #1e09344e
@patch(cls_method=True)
async def remote(cls:CDP, port:int=9223, debug:bool=None):
    "Connect via Chrome remote debugging HTTP endpoint"
    async with httpx.AsyncClient() as client:
        url = (await client.get(f'http://localhost:{port}/json/version')).json()['webSocketDebuggerUrl']
    return await cls.connect(wsconn=url, debug=debug)

# %% ../nbs/00_core.ipynb #65405bf6
_chrome_bins = dict(Darwin=['/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',
    '/Applications/Chromium.app/Contents/MacOS/Chromium'],
    Linux=['google-chrome', 'chromium', 'chromium-browser'])

def chrome_bin():
    "Path of the installed Chrome/Chromium binary (`$FASTCDP_CHROME` overrides)"
    if (p := os.environ.get('FASTCDP_CHROME')): return p
    bins = _chrome_bins.get(platform.system(), _chrome_bins['Linux'])
    b = first(b for b in bins if Path(b).exists() or shutil.which(b))
    if not b: raise FileNotFoundError('No Chrome or Chromium found; set FASTCDP_CHROME')
    return b

# %% ../nbs/00_core.ipynb #e2ed788d
@patch(cls_method=True)
async def launch(cls:CDP,
    user_data_dir:str|Path=None, # Profile dir; `~/.cache/fastcdp/profile` if None
    headless:bool=False, # Run without a visible window?
    debug:bool=None, # Print protocol events?
    timeout:int=10, # Seconds to wait for the debug endpoint
    reuse:bool=True, # Connect to an instance already running on this profile? (Else raise)
):
    "Launch the installed Chrome CDP-ready on its own profile dir, and connect to it"
    d = Path(user_data_dir) if user_data_dir else Path.home()/'.cache'/'fastcdp'/'profile'
    d.mkdir(parents=True, exist_ok=True)
    f = d/'DevToolsActivePort'
    if f.exists():
        ci = cdp_conninfo(d=d)
        port = int(ci.split('/', 1)[0])
        if is_port_free(port): f.unlink()   # provably stale: nothing is listening
        elif not reuse: raise RuntimeError(f'{f} names a running Chrome on port {port}; pass reuse=True to connect to it')
        else:
            try: self = await cls.connect(wsconn=ci, debug=debug)
            except (OSError, websockets.WebSocketException) as e: raise RuntimeError(f'port {port} from {f} is in use but not connectable; is something other than Chrome using it?') from e
            self.proc,self.port = None,port
            return self
    args = [f'--user-data-dir={d}', '--remote-debugging-port=0', '--no-first-run', '--no-default-browser-check']
    if headless: args.append('--headless=new')
    proc = await asyncio.create_subprocess_exec(chrome_bin(), *args,
        stdout=asyncio.subprocess.DEVNULL, stderr=asyncio.subprocess.DEVNULL)
    deadline = asyncio.get_event_loop().time() + timeout
    while not f.exists():
        if proc.returncode is not None: raise RuntimeError('Chrome exited at launch (already running on this profile dir?)')
        if asyncio.get_event_loop().time() > deadline: raise TimeoutError('Timed out waiting for Chrome debug endpoint')
        await asyncio.sleep(0.05)
    ci = cdp_conninfo(d=d)
    self = await cls.connect(wsconn=ci, debug=debug)
    self.proc,self.port = proc, int(ci.split('/', 1)[0])
    return self

# %% ../nbs/00_core.ipynb #7055c385
@patch
async def quit(self:CDP):
    "Quit the browser, wait until it has released its debug port, and close the connection"
    try: await asyncio.wait_for(self('Browser.close'), 2)
    except (TimeoutError, websockets.ConnectionClosed): pass
    await self.close()
    if (proc := getattr(self, 'proc', None)) is not None: await proc.wait()
    elif (port := getattr(self, 'port', None)): await wait_port_free_async(port, max_wait=5)

# %% ../nbs/00_core.ipynb #e7db5a91
class Targets(list):
    "Page targets as attribute-access rows, one line per target"
    def __repr__(self): return '\n'.join(f"{t.targetId} {'*' if t.attached else ' '} {t.url[:80]}" for t in self)

@patch(as_prop=True)
async def pages(self:CDP)->Targets: # Rows with `targetId`, `url`, `title`, `attached`, ...; `*` marks attached
    "The browser's open page targets"
    return Targets(AttrDict(t) for t in (await self('Target.getTargets')) if t['type'] == 'page')

# %% ../nbs/00_core.ipynb #7b94f2b8
_domains = {d['domain']: d for d in _cdp_domains}

def _find_cmd(domain, method):
    d = _domains.get(domain, {})
    return first(c for c in d.get('commands', []) if c['name'] == method)

def _cmd_sig(cmd):
    _P = inspect.Parameter
    ps = [_P(p['name'], _P.KEYWORD_ONLY, default=None if p.get('optional') else _P.empty) for p in cmd.get('parameters', [])]
    return inspect.Signature([_P('sid', _P.KEYWORD_ONLY, default=None)] + ps)

def _cmd_doc(domain, method, cmd):
    doc = f"{domain}.{method}"
    if cmd.get('description'): doc += f" - {cmd['description']}"
    for p in cmd.get('parameters', []):
        opt = ' (optional)' if p.get('optional') else ''
        doc += f"\n  {p['name']}{opt}: {p.get('description', '')}"
    return doc

# %% ../nbs/00_core.ipynb #1c2d0198
class CDPMethod:
    def __init__(self, cdp, domain, method):
        store_attr()
        if (cmd := _find_cmd(domain, method)):
            self.__doc__ = _cmd_doc(domain, method, cmd)
            self.__signature__ = _cmd_sig(cmd)

    async def __call__(self, sid=None, **kw): return await self.cdp(f'{self.domain}.{self.method}', sid=sid, **kw)

class CDPDomain:
    def __init__(self, cdp, domain): store_attr()

    def __getattr__(self, method):
        if method.startswith('_'): raise AttributeError()
        return CDPMethod(self.cdp, self.domain, method)

    def __dir__(self):
        d = _domains.get(self.domain, {})
        return [c['name'] for c in d.get('commands', [])] + [e['name'] for e in d.get('events', [])]

# %% ../nbs/00_core.ipynb #3c348501
@patch
async def attach(self:CDP,
    tid:str, # Target id, e.g. from `pages`
)->str: # Session id, for `sid` arguments
    "Attach to target `tid`"
    return await self.target.attachToTarget(targetId=tid, flatten=True)

@patch
async def eval(self:CDP,
    expr:str, # JS expression; a promise result is awaited
    sid:str=None, # Session to evaluate in
): # The result as a Python value, for JSON-serializable results
    "Evaluate `expr` in the page, raising on a JS exception"
    r = await self.runtime.evaluate(sid=sid, expression=expr, returnByValue=True, awaitPromise=True)
    if 'exceptionDetails' in r: raise RuntimeError(nested_idx(r, 'exceptionDetails', 'exception', 'description') or r['exceptionDetails']['text'])
    return r.get('value')

# %% ../nbs/00_core.ipynb #5b1d1bb4
@patch
@asynccontextmanager
async def on(self:CDP, event:str):
    q = asyncio.Queue()
    self._events.setdefault(event, []).append(q)
    try: yield q
    finally: self._events[event].remove(q)

@patch
async def wait_event(self:CDP, event:str, timeout:int=10):
    async with self.on(event) as q:
        return await asyncio.wait_for(q.get(), timeout)


# %% ../nbs/00_core.ipynb #1d2f0ec0
@patch
async def wait_load(self:CDP, sid:str=None, timeout:int=10):
    while True:
        e = await self.wait_event('Page.lifecycleEvent', timeout=timeout)
        print(e)
        if e['params'].get('name') == 'networkIdle': return

@patch
async def wait_for(self:CDP, expr:str, sid:str=None, timeout:int=10):
    "Wait for JS expression to be truthy, return its value"
    deadline = asyncio.get_event_loop().time() + timeout
    while asyncio.get_event_loop().time() < deadline:
        r = await self.eval(expr, sid)
        if r: return r
        await asyncio.sleep(0.05)
    raise TimeoutError(f'Timed out waiting for: {expr}')

@patch
async def wait_for_selector(self:CDP, sel:str, sid:str=None, timeout:int=10):
    "Wait for CSS selector to match an element"
    return await self.wait_for(f'!!document.querySelector("{sel}")', sid, timeout)

# %% ../nbs/00_core.ipynb #e9e3f54d
def _copy_meta(src, dest):
    if hasattr(src, '__doc__'): dest.__doc__ = src.__doc__
    if hasattr(src, '__signature__'):
        dest.__signature__ = src.__signature__.replace(
            parameters=[p for p in src.__signature__.parameters.values() if p.name != 'sid'])
    return dest

# %% ../nbs/00_core.ipynb #1d63dba1
class PageDomain:
    def __init__(self, sid, domain): store_attr()
    def __dir__(self): return self.domain.__dir__()

    def __getattr__(self, name):
        if name.startswith('_'): raise AttributeError(name)
        m = getattr(self.domain, name)
        async def _f(**kw): return await m(sid=self.sid, **kw)
        return _copy_meta(m, _f)

# %% ../nbs/00_core.ipynb #8fb12710
class Page:
    def __init__(self, cdp:CDP, t:str, sid:str, owned:bool=False): store_attr()

    @classmethod
    async def new(cls, t:str=None, cdp:CDP=None, **kwargs):
        if not cdp: cdp,owned = await CDP.connect(**kwargs),True
        else: owned = False
        if not t: t = await cdp.target.createTarget(url='about:blank')
        sid = await cdp.attach(t)
        self = cls(cdp, t, sid, owned=owned)
        await cdp.page.enable(sid=sid)
        return self

    def __getattr__(self, name):
        if name.startswith('_'): raise AttributeError(name)
        o = getattr(self.cdp, name)
        if isinstance(o, CDPDomain): return PageDomain(self.sid, o)
        if not callable(o): return o
        async def _f(*a, **kw): return await o(*a, sid=self.sid, **kw)
        return _copy_meta(o, _f)

    async def close(self):
        # Ignore errors if already closed
        try: await self.cdp.target.closeTarget(targetId=self.t)
        except RuntimeError: pass
        if self.owned: await self.cdp.close()

    @property
    def is_open(self): return self.cdp.is_open

    def __dir__(self): return self.cdp.__dir__()

# %% ../nbs/00_core.ipynb #bf90b19e
@patch
async def active_page(self:CDP):
    "A `Page` driving the focused tab, or `None` when no tab has focus"
    for t in (await self('Target.getTargets')):
        if t['type'] != 'page': continue
        sid = await self.attach(t['targetId'])
        if await self.eval('document.hasFocus()', sid): return Page(self, t['targetId'], sid)
        await self.target.detachFromTarget(sessionId=sid)

@patch(cls_method=True)
async def remote_page(cls:CDP, port:int=9223, debug:bool=None):
    "Connect via remote debugging and return a `Page` for the active tab"
    cdp = await cls.remote(port=port, debug=debug)
    page = await cdp.active_page()
    if not page: raise RuntimeError("No focused page found")
    page.owned = True
    return page


# %% ../nbs/00_core.ipynb #3d0570b5
@patch
async def new_page(self:CDP):
    "Create a new tab, return Page"
    t = await self.target.createTarget(url='about:blank')
    await asyncio.sleep(0.1)
    return await Page.new(t, self)

# %% ../nbs/00_core.ipynb #8930594b
@patch
async def attach_page(self:CDP,
    tid:str, # Target id, e.g. from `pages`
)->Page: # Proxy driving that tab
    "Attach to the existing tab `tid`"
    return await Page.new(tid, self)

# %% ../nbs/00_core.ipynb #0bf3d185
@patch
async def wait_for_ready(self:CDP, sid:str=None, timeout:int=10, idle_ms:int=500):
    "Wait until network is idle for idle_ms"
    await self.network.enable(sid=sid)
    deadline = asyncio.get_event_loop().time() + timeout
    while asyncio.get_event_loop().time() < deadline:
        async with self.on('Network.requestWillBeSent') as q:
            try: await asyncio.wait_for(q.get(), timeout=idle_ms/1000)
            except asyncio.TimeoutError: return
    raise TimeoutError('Timed out waiting for network idle')


@patch
@asynccontextmanager
async def wait_ready(self:CDP, sid:str=None, timeout:int=10, idle_ms:int=500):
    "Context manager: subscribes before action, waits for load+idle after"
    await self.page.setLifecycleEventsEnabled(sid=sid, enabled=True)
    async with self.on('Page.loadEventFired') as q_load:
        yield
        await asyncio.wait_for(q_load.get(), timeout=timeout)
        await self.wait_for_ready(sid=sid, timeout=timeout, idle_ms=idle_ms)

@patch
async def goto(self:CDP, url:str, sid:str=None, **kwargs):
    "Navigate to url and wait for load+idle"
    async with self.wait_ready(sid=sid, **kwargs): await self.page.navigate(sid=sid, url=url)

# %% ../nbs/00_core.ipynb #2cea0ba8
@patch
async def screenshot(self:CDP, sid:str=None, full:bool=False):
    "Screenshot of the viewport, or the whole scrollable page if `full`"
    from IPython.display import Image
    b64 = await self.page.captureScreenshot(sid=sid, format='png', captureBeyondViewport=full)
    return Image(base64.b64decode(b64))

# %% ../nbs/00_core.ipynb #786aa6ef
class AXNode:
    "Chrome accessibility tree node with compact repr"
    def __init__(self, raw:dict):
        self.role = nested_idx(raw, 'role', 'value') or ''
        self.name = nested_idx(raw, 'name', 'value') or ''
        self.props = {p['name']: nested_idx(p, 'value', 'value') for p in raw.get('properties', [])}
        self.children = []
        self.node_id = raw.get('nodeId')
        self.backend_id = raw.get('backendDOMNodeId')
        self.ignored = raw.get('ignored', False)
        self._raw = raw

    def _repr_markdown_(self, depth=0):
        pre = '  ' * depth
        ps = ''.join(f' `{k}={v}`' for k,v in self.props.items() if v not in (False, None, '', 'false'))
        bid = f' [#{self.backend_id}]' if self.backend_id else ''
        line = f'{pre}- **{self.role}** "{self.name}"{ps}{bid}'
        return '\n'.join([line] + [c._repr_markdown_(depth+1) for c in self.children])

    __str__ = __repr__ = _repr_markdown_

class AXTree(AXNode):
    def _repr_markdown_(self): return f'<div class="prose">\n\n{super()._repr_markdown_(0)}\n\n</div>'

# %% ../nbs/00_core.ipynb #ce180f22
def _simplify(node):
    node.children = [n for c in node.children for n in _simplify(c)]
    if node.role in ('none', 'generic', 'paragraph') and not node.name:
        if not node.children: return []
        return node.children  # splice children up
    return [node]

def build_ax_tree(nodes:list):
    "Build AXNode tree from flat CDP accessibility node list"
    by_id = {}
    for raw in nodes:
        n = AXNode(raw)
        by_id[n.node_id] = n
    for raw in nodes:
        parent = by_id.get(raw.get('nodeId'))
        for cid in raw.get('childIds', []):
            if (child := by_id.get(cid)): parent.children.append(child)
    if not nodes: return
    root = by_id.get(nodes[0]['nodeId'])
    if not (result := _simplify(root)): return None
    result = result[0]
    result.__class__ = AXTree
    return result

# %% ../nbs/00_core.ipynb #2a418b3b
@patch
async def ax_tree(self:CDP, sid:str=None):
    "Get accessibility tree for session"
    await self.accessibility.enable(sid=sid)
    return build_ax_tree(await self.accessibility.getFullAXTree(sid=sid))

# %% ../nbs/00_core.ipynb #92b49b0c
@patch
def find(self:AXNode, role:str=None, name:str=None):
    "Find first descendant matching role and/or name substring"
    if (not role or role == self.role) and (not name or name in self.name): return self
    for c in self.children:
        if (r := c.find(role, name)): return r

@patch
def find_id(self:AXNode, role:str=None, name:str=None):
    "Find first descendant matching role and/or name substring"
    res = self.find(role, name)
    return res.backend_id if res else None

@patch
def find_all(self:AXNode, role:str=None, name:str=None):
    "Find all descendants matching role and/or name substring"
    res = []
    if (not role or role == self.role) and (not name or name in self.name): res.append(self)
    for c in self.children: res += c.find_all(role, name)
    return res

# %% ../nbs/00_core.ipynb #6639fea3
@patch
async def js_node(self:CDP,
    fn:str, # JS function declaration, called with the node as `this`
    backendNodeId:int, # Node, e.g. from `AXNode.find_id`
    sid:str=None, # Session the node lives in
):
    "Call function `fn` on a DOM node, returning the protocol result"
    obj = await self.DOM.resolveNode(sid=sid, backendNodeId=backendNodeId)
    return await self.runtime.callFunctionOn(sid=sid, functionDeclaration=fn,
                                              objectId=obj['objectId'])

@patch
async def js_node_run(self:CDP,
    code:str, # JS statements, with the node as `this`
    backendNodeId:int, # Node, e.g. from `AXNode.find_id`
    sid:str=None, # Session the node lives in
):
    "Run `code` with a DOM node as `this`"
    return await self.js_node(f'function() {{ {code} }}', backendNodeId, sid=sid)

@patch
async def click(self:CDP,
    backendNodeId:int, # Node, e.g. from `AXNode.find_id`
    sid:str=None, # Session the node lives in
):
    "Click a DOM node"
    await self.js_node_run('this.click()', backendNodeId, sid=sid)

# %% ../nbs/00_core.ipynb #f512a6f2
@patch
async def fill_text(self:CDP, backendNodeId:int, text:str, sid:str=None):
    await self.DOM.focus(sid=sid, backendNodeId=backendNodeId)
    await self.input.insertText(sid=sid, text=text)

# %% ../nbs/00_core.ipynb #99fda301
@patch
async def click_and_wait(self:CDP, backendNodeId:int, sid:str=None, **kwargs):
    "Click element and wait for load+idle"
    async with self.wait_ready(sid=sid, **kwargs): await self.js_node_run('this.click()', backendNodeId, sid=sid)

# %% ../nbs/00_core.ipynb #90320ba6
class _EvtBuf:
    "Accumulate events from subscribed queues, draining on read"
    def __init__(self, cdp, *events):
        self.q,self.items = asyncio.Queue(),[]
        for e in events: cdp._events.setdefault(e, []).append(self.q)
    def drain(self):
        while not self.q.empty(): self.items.append(self.q.get_nowait())
        return self.items

def _fmt_console(m):
    p = m['params']
    if (d := p.get('exceptionDetails')): return f"error: {nested_idx(d, 'exception', 'description') or d['text']}"
    return f"{p['type']}: {' '.join(str(a.get('value', a.get('description', ''))) for a in p['args'])}"

@patch
async def start_console(self:CDP, sid:str=None):
    "Enable and start buffering console messages and uncaught exceptions"
    await self.runtime.enable(sid=sid)
    self._console = _EvtBuf(self, 'Runtime.consoleAPICalled', 'Runtime.exceptionThrown')

@patch
async def console(self:CDP, pattern:str=None, sid:str=None):
    "Console/exception messages buffered since `start_console`, filtered by regex `pattern`"
    msgs = self._console.drain()
    if sid: msgs = [m for m in msgs if m.get('sessionId') == sid]
    res = [_fmt_console(m) for m in msgs]
    return [s for s in res if re.search(pattern, s)] if pattern else res

# %% ../nbs/00_core.ipynb #d096afc1
@patch
async def start_network(self:CDP, sid:str=None):
    "Enable and start buffering network responses"
    await self.network.enable(sid=sid)
    self._network = _EvtBuf(self, 'Network.responseReceived')

@patch
async def requests(self:CDP, pattern:str=None, sid:str=None):
    "(status,url,requestId) of responses buffered since `start_network`, url filtered by regex `pattern`"
    msgs = self._network.drain()
    if sid: msgs = [m for m in msgs if m.get('sessionId') == sid]
    res = [(p['response']['status'], p['response']['url'], p['requestId']) for m in msgs for p in [m['params']]]
    return [r for r in res if re.search(pattern, r[1])] if pattern else res

@patch
async def response_body(self:CDP, requestId:str, sid:str=None):
    "Body of a response seen by `start_network`, decoded if base64"
    r = await self.network.getResponseBody(sid=sid, requestId=requestId)
    return base64.b64decode(r['body']).decode() if r['base64Encoded'] else r['body']

# %% ../nbs/00_core.ipynb #ba9aa533
@patch
async def handle_dialogs(self:CDP, accept:bool=True, text:str=None, sid:str=None):
    "Auto-respond to JS dialogs from now on, recording (type,message) in `dialogs`"
    await self.page.enable(sid=sid)
    self.dialogs = []
    q = asyncio.Queue()
    self._events.setdefault('Page.javascriptDialogOpening', []).append(q)
    async def _h():
        while True:
            m = await q.get()
            p = m['params']
            self.dialogs.append((p['type'], p['message']))
            kw = dict(accept=accept)
            if text is not None: kw['promptText'] = text
            await self.page.handleJavaScriptDialog(sid=m.get('sessionId'), **kw)
    self._dialog_task = asyncio.create_task(_h())

# %% ../nbs/00_core.ipynb #3e7c8028
@patch
async def select_option(self:CDP, backendNodeId:int, value:str, sid:str=None):
    "Set a `<select>` element's value and fire its change event"
    await self.js_node_run(f'this.value = {json.dumps(value)}; this.dispatchEvent(new Event("change", {{bubbles:true}}))', backendNodeId, sid=sid)

@patch
async def wait_for_text(self:CDP, text:str, present:bool=True, sid:str=None, timeout:int=10):
    "Wait for `text` to appear in (with `present=False`, disappear from) the page body"
    expr = f'document.body.innerText.includes({json.dumps(text)})'
    return await self.wait_for(expr if present else f'!({expr})', sid, timeout)

# %% ../nbs/00_core.ipynb #904883ee
def cdp_yolo():
    "Allow all CDP classes in safepyrun"
    from pyskills import allow
    allow({CDP:..., CDPDomain:..., CDPMethod:...})
    allow({PageDomain:..., Page:..., AXNode:..., AXTree:...})
