"""Drive the user's everyday Chrome through a companion extension

Docs: https://AnswerDotAI.github.io/fastcdp/ext.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_ext.ipynb.

# %% auto #0
__all__ = ['ExtChannel', 'ExtCDP', 'ExtPage', 'cdp_yolo']

# %% ../nbs/01_ext.ipynb #a6cd09cc
from fastcore.utils import *
import asyncio, json, websockets
from urllib.parse import urlparse, parse_qsl
from .core import *
import fastcdp.core

# %% ../nbs/01_ext.ipynb #4bd37f41
def _probe_ok(conn, req):
    "Answer the extension's plain-HTTP port probe instead of attempting a handshake"
    if 'Upgrade' not in req.headers: return conn.respond(200, 'fastcdp\n')

class ExtChannel:
    "Listen for the extension to dial in, then speak duplex JSON frames with it"
    def __init__(self): self._replies,self.events,self._id = {},asyncio.Queue(),0

    @classmethod
    async def listen(cls,
        port:int=34654, # Port to listen on (0 picks a free one; see `port`)
        host:str='127.0.0.1', # Interface to bind
        token:str=None # If set, the extension must dial with a matching `?token=`
    ):
        "Start listening for the extension to dial `ws://host:port/?token=`"
        self = cls()
        self._token = token
        self._peer = asyncio.get_running_loop().create_future()
        self._server = await websockets.serve(self._handler, host, port, process_request=_probe_ok)
        return self

    async def _handler(self, ws):
        q = dict(parse_qsl(urlparse(ws.request.path).query))
        if self._token and q.get('token') != self._token: return await ws.close(4003, 'bad token')
        self._ws = ws
        if not self._peer.done(): self._peer.set_result(ws)
        try:
            async for frame in ws:
                msg = dict2obj(json.loads(frame))
                if (f := self._replies.pop(msg.get('id'), None)): f.set_result(msg)
                else: await self.events.put(msg)
        except websockets.ConnectionClosed: pass

    async def wait_peer(self, timeout:float=None):
        "Wait until an extension has connected"
        await asyncio.wait_for(asyncio.shield(self._peer), timeout)

    async def send(self, **msg): await self._ws.send(json.dumps(msg))

    async def request(self, timeout:int=15, **msg):
        "Send `msg` with a correlation `id` and await the reply frame bearing that id"
        self._id += 1
        mid = msg['id'] = self._id
        f = asyncio.get_running_loop().create_future()
        self._replies[mid] = f
        try:
            await self.send(**msg)
            return await asyncio.wait_for(f, timeout)
        finally: self._replies.pop(mid, None)

    @property
    def port(self): return self._server.sockets[0].getsockname()[1]

    async def close(self):
        self._server.close()
        await self._server.wait_closed()

    @property
    def is_open(self): return getattr(self, '_ws', None) is not None and self._ws.state.name == 'OPEN'

# %% ../nbs/01_ext.ipynb #451d9654
class ExtCDP(CDP):
    "CDP spoken with a companion extension, as JSON frames over a channel to it"
    @classmethod
    async def connect(cls,
        chan:ExtChannel, # A connected channel to the extension
        debug:bool=None # Print events as they arrive?
    ):
        self = cls(debug=debug)
        self.chan = chan
        self._pump = asyncio.create_task(self._pump_events())
        return self

    @classmethod
    async def listen(cls,
        port:int=34654, # Port the extension dials
        token:str=None, # Shared secret the extension must present
        timeout:float=None, # Max seconds to wait for the extension
        debug:bool=None # Print events as they arrive?
    ):
        "Listen on `port` and speak CDP with the first extension that dials in"
        chan = await ExtChannel.listen(port=port, token=token)
        await chan.wait_peer(timeout)
        return await cls.connect(chan, debug=debug)

    async def _pump_events(self):
        while True:
            msg = obj2dict(await self.chan.events.get())
            if 'method' not in msg: continue
            if (tid := msg.pop('tabId', None)) is not None: msg['sessionId'] = tid
            self._dispatch(msg)

    async def _send(self, msg):
        if (sid := msg.pop('sessionId', None)) is not None: msg['tabId'] = sid
        return obj2dict(await self.chan.request(**msg))

    async def _action(self, action, **kw):
        "Extension-side lifecycle operations that have no CDP equivalent"
        r = await self.chan.request(action=action, **kw)
        if 'error' in r: raise RuntimeError(f"{action}: {r['error']}")
        return obj2dict(r['result'])

    async def close(self):
        self._pump.cancel()
        if (t := getattr(self, '_dialog_task', None)): t.cancel()
        await self.chan.close()

    @property
    def is_open(self): return self.chan.is_open

# %% ../nbs/01_ext.ipynb #25d27b88
class ExtPage(Page):
    "A `Page` whose tab is closed through the extension"
    async def close(self):
        try: await self.cdp._action('close-tab', tabId=self.t)
        except RuntimeError: pass

@patch
async def new_page(self:ExtCDP, url:str='about:blank', active:bool=False):
    "Open a new browser tab and return a `Page` driving it"
    tid = (await self._action('new-tab', url=url, active=active))['tabId']
    await self.page.enable(sid=tid)
    return ExtPage(self, tid, tid)

@patch
async def attach_page(self:ExtCDP, tid:int|str):
    "Attach to an existing tab and return a `Page` driving it; takes the integer `tabId` or hex target `id` from `pages`"
    if isinstance(tid, str):
        tabs = {t['id']:t['tabId'] for t in await self.pages}
        if tid not in tabs: raise KeyError(f'no tab with target id {tid}')
        tid = tabs[tid]
    tid = (await self._action('attach', tabId=tid))['tabId']
    await self.page.enable(sid=tid)
    return ExtPage(self, tid, tid)

@patch(as_prop=True)
async def pages(self:ExtCDP):
    return [t for t in await self._action('get-targets') if t.get('type')=='page']

@patch
async def active_page(self:ExtCDP):
    "A `Page` driving the frontmost tab: the active tab of the last-focused window"
    return await self.attach_page((await self._action('active-tab'))['tabId'])

# %% ../nbs/01_ext.ipynb #42263328
def cdp_yolo():
    "Allow all CDP classes in safepyrun, including the extension transport"
    from pyskills import allow
    fastcdp.core.cdp_yolo()
    allow({ExtChannel:..., ExtCDP:..., ExtPage:...})
