"""Create a CDP Chrome launcher or install a separate Chrome for Testing

Docs: https://AnswerDotAI.github.io/fastcdp/setup.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_setup.ipynb.

# %% auto #0
__all__ = ['chrome_path', 'testing_chrome', 'install_chrome', 'main']

# %% ../nbs/02_setup.ipynb #18f17f00
from fastcore.utils import *
from fastcore.script import call_parse
import platform, subprocess, shutil, httpx
from importlib.resources import files
from tempfile import TemporaryDirectory
from zipfile import ZipFile

# %% ../nbs/02_setup.ipynb #c2d91e18
def chrome_path():
    "Find the installed Chrome (or Chromium) executable"
    sys = platform.system()
    if sys == 'Darwin': return Path('/Applications/Google Chrome.app/Contents/MacOS/Google Chrome')
    if sys == 'Windows':
        cands = [Path(os.environ.get(v, ''))/'Google/Chrome/Application/chrome.exe'
            for v in ('PROGRAMFILES', 'PROGRAMFILES(X86)', 'LOCALAPPDATA')]
        if (p := first(cands, Path.is_file)): return p
        raise FileNotFoundError('chrome.exe not found')
    for n in ('google-chrome', 'google-chrome-stable', 'chromium', 'chromium-browser'):
        if (p := shutil.which(n)): return Path(p)
    raise FileNotFoundError('chrome not found on PATH')

# %% ../nbs/02_setup.ipynb #33c775b5
_PLIST = """<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0"><dict>
  <key>CFBundleName</key><string>{name}</string>
  <key>CFBundleDisplayName</key><string>{name}</string>
  <key>CFBundleIdentifier</key><string>ai.answer.fastcdp.{ident}</string>
  <key>CFBundleExecutable</key><string>launch</string>
  <key>CFBundleIconFile</key><string>icon</string>
  <key>CFBundlePackageType</key><string>APPL</string>
  <key>CFBundleVersion</key><string>1.0</string>
</dict></plist>
"""

def _ident(name): return re.sub(r'\W+', '-', name.lower()).strip('-')

def _mac_app(chrome, name, port, profile, dest):
    app = dest/f'{name}.app'
    (app/'Contents/MacOS').mkdir(parents=True, exist_ok=True)
    (app/'Contents/Resources').mkdir(parents=True, exist_ok=True)
    (app/'Contents/Info.plist').write_text(_PLIST.format(name=name, ident=_ident(name)))
    scr = app/'Contents/MacOS/launch'
    # `arch -arm64`: a script-bundle executable runs under Rosetta, and Chrome would inherit its x86_64 slice
    scr.write_text(f'#!/bin/sh\nexec arch -arm64 "{chrome}" --remote-debugging-port={port} --user-data-dir="{profile}" --no-first-run --no-default-browser-check "$@"\n')
    scr.chmod(0o755)
    shutil.copy(files('fastcdp')/'icons/cdp-chrome.icns', app/'Contents/Resources/icon.icns')
    return app

# %% ../nbs/02_setup.ipynb #0e47f9c1
def _linux_app(chrome, name, port, profile, dest):
    ic = dest/'icons/hicolor/256x256/apps/cdp-chrome.png'
    ic.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy(files('fastcdp')/'icons/cdp-chrome.png', ic)
    desk = dest/'applications'/f'{_ident(name)}.desktop'
    desk.parent.mkdir(parents=True, exist_ok=True)
    # chkstyle: ignore-node
    desk.write_text(f'''[Desktop Entry]
Type=Application
Name={name}
Exec="{chrome}" --remote-debugging-port={port} --user-data-dir="{profile}" --no-first-run --no-default-browser-check
Icon=cdp-chrome
Terminal=false
Categories=Development;
''')
    return desk

# %% ../nbs/02_setup.ipynb #e152d58b
def _win_app(chrome, name, port, profile, dest):
    ic = Path(profile)/'cdp-chrome.ico'
    ic.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy(files('fastcdp')/'icons/cdp-chrome.ico', ic)
    dest.mkdir(parents=True, exist_ok=True)
    lnk = dest/f'{name}.lnk'
    ps = f'''$s = (New-Object -ComObject WScript.Shell).CreateShortcut('{lnk}')
$s.TargetPath = '{chrome}'
$s.Arguments = '--remote-debugging-port={port} --user-data-dir="{profile}" --no-first-run --no-default-browser-check'
$s.IconLocation = '{ic}'
$s.Save()'''
    subprocess.run(['powershell', '-NoProfile', '-Command', ps], check=True)
    return lnk

# %% ../nbs/02_setup.ipynb #a5d4adc1
_CFT = 'https://googlechromelabs.github.io/chrome-for-testing'

def _testing_platform():
    sys,arch = platform.system(),platform.machine().lower()
    plats = dict(Darwin=dict(arm64='mac-arm64', x86_64='mac-x64'), Linux=dict(aarch64='linux-arm64', arm64='linux-arm64', x86_64='linux64'),
        Windows=dict(amd64='win64', x86='win32'))
    if (p := plats.get(sys, {}).get(arch)): return p
    raise RuntimeError(f'Unsupported Chrome for Testing platform: {sys} {arch}')

def _testing_root(): return Path.home()/'.cache/fastcdp/chrome-for-testing'/_testing_platform()

def _testing_exe():
    plat = _testing_platform()
    exe = 'Google Chrome for Testing.app/Contents/MacOS/Google Chrome for Testing' if plat.startswith('mac-') else (
        'chrome.exe' if plat.startswith('win') else 'chrome')
    return Path(f'chrome-{plat}')/exe

def _chrome_version(version):
    if not re.fullmatch(r'\d+\.\d+\.\d+\.\d+', version): raise ValueError(f'Expected an exact Chrome version, got {version!r}')
    return version

# %% ../nbs/02_setup.ipynb #9d624582
def testing_chrome(version:str=None):
    "Executable for an installed Chrome for Testing; never falls back to the user's Chrome or downloads"
    root = _testing_root()
    if version is None and (root/'current').is_file(): version = (root/'current').read_text().strip()
    if version is not None:
        chrome = root/_chrome_version(version)/_testing_exe()
        if chrome.is_file(): return chrome
    raise FileNotFoundError(f'Chrome for Testing is not installed; run fastcdp-setup --install {version or "stable"}')

# %% ../nbs/02_setup.ipynb #9c06c6b3
def _extract_chrome(archive, dest):
    # ditto preserves macOS framework symlinks and executable permissions.
    if platform.system() == 'Darwin': return subprocess.run(['ditto', '-x', '-k', str(archive), str(dest)], check=True)
    with ZipFile(archive) as z:
        z.extractall(dest)
        if platform.system() != 'Windows':
            for info in z.infolist():
                if (mode := info.external_attr >> 16 & 0o777): (dest/info.filename).chmod(mode)

def _chrome_deps(chrome):
    if platform.system() != 'Linux': return
    deps = (chrome.parent/'deb.deps').read_text().splitlines()
    cmd = ([] if os.geteuid() == 0 else ['sudo']) + ['apt-get']
    subprocess.run(cmd + ['update'], check=True)
    subprocess.run(cmd + ['satisfy', '-y', '--no-install-recommends'] + [d for d in deps if d.strip()], check=True)

def install_chrome(
    version:str='stable', # Release channel or exact four-part version
    with_deps:bool=False, # Also install Linux system dependencies using apt-get (and sudo if needed)
):
    "Download and select Chrome for Testing, without changing desktop launchers or profiles"
    channel = version.title() if version.lower() in ('stable', 'beta', 'dev', 'canary') else None
    if not channel: _chrome_version(version)
    root = _testing_root()
    root.mkdir(parents=True, exist_ok=True)
    with httpx.Client(timeout=60, follow_redirects=True) as client, TemporaryDirectory(prefix='.install-', dir=root) as tmp:
        if channel or not (root/version/_testing_exe()).is_file():
            manifest = 'last-known-good-versions-with-downloads' if channel else version
            response = client.get(f'{_CFT}/{manifest}.json')
            response.raise_for_status()
            release = response.json()
            if channel: release = release['channels'][channel]
            version = _chrome_version(release['version'])
            asset = first(a for a in release['downloads']['chrome'] if a['platform'] == _testing_platform())
            if not asset: raise RuntimeError(f'Chrome {version} has no {_testing_platform()} build')
            dest = root/version
            if not (dest/_testing_exe()).is_file():
                archive,unpacked = Path(tmp)/'chrome.zip',Path(tmp)/'unpacked'
                with client.stream('GET', asset['url']) as response, archive.open('wb') as f:
                    response.raise_for_status()
                    for chunk in response.iter_bytes(): f.write(chunk)
                _extract_chrome(archive, unpacked)
                if not (unpacked/_testing_exe()).is_file(): raise RuntimeError('Chrome archive has no browser executable')
                unpacked.rename(dest)
        chrome = root/version/_testing_exe()
        if with_deps: _chrome_deps(chrome)
        selected = Path(tmp)/'current'
        selected.write_text(version)
        selected.replace(root/'current')
    return chrome


# %% ../nbs/02_setup.ipynb #041b4876
@call_parse
def main(
    port:int=9223, # Debug port (`CDP.remote`'s default; 9222 would clash with the everyday browser's built-in debugging)
    profile:str=None, # Chrome profile dir (default: `~/.cache/fastcdp/cdp-chrome`)
    name:str='CDP Chrome', # Launcher name
    install:str=None, # Install Chrome for Testing instead of a launcher: stable, beta, dev, canary, or exact version
    with_deps:bool=False, # Also install Linux dependencies (requires --install; may invoke sudo)
):
    "Create the CDP Chrome launcher, or use --install to provision a separate Chrome for Testing"
    if install:
        res = install_chrome(install, with_deps=with_deps)
        print(res)
        return res
    if with_deps: raise ValueError('--with-deps requires --install')
    profile = Path(profile) if profile else Path.home()/'.cache/fastcdp/cdp-chrome'
    chrome, sys = chrome_path(), platform.system()
    if sys == 'Darwin': res = _mac_app(chrome, name, port, profile, Path.home()/'Applications')
    elif sys == 'Linux': res = _linux_app(chrome, name, port, profile, Path.home()/'.local/share')
    elif sys == 'Windows': res = _win_app(chrome, name, port, profile, Path(os.environ['APPDATA'])/'Microsoft/Windows/Start Menu/Programs')
    else: raise RuntimeError(f'Unsupported OS: {sys}')
    print(f'Created {res}\nConnect with: cdp = await CDP.remote({port})')
    return res
