"""Create a "CDP Chrome" launcher for a debug-enabled, automation-only Chrome

Docs: https://AnswerDotAI.github.io/fastcdp/setup.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_setup.ipynb.

# %% auto #0
__all__ = ['chrome_path', 'main']

# %% ../nbs/02_setup.ipynb #18f17f00
from fastcore.utils import *
from fastcore.script import call_parse
import platform, subprocess, shutil
from importlib.resources import files

# %% ../nbs/02_setup.ipynb #c2d91e18
def chrome_path():
    "Find the installed Chrome (or Chromium) executable"
    sys = platform.system()
    if sys == 'Darwin': return Path('/Applications/Google Chrome.app/Contents/MacOS/Google Chrome')
    if sys == 'Windows':
        cands = [Path(os.environ.get(v, ''))/'Google/Chrome/Application/chrome.exe'
                 for v in ('PROGRAMFILES', 'PROGRAMFILES(X86)', 'LOCALAPPDATA')]
        if (p := first(cands, Path.is_file)): return p
        raise FileNotFoundError('chrome.exe not found')
    for n in ('google-chrome', 'google-chrome-stable', 'chromium', 'chromium-browser'):
        if (p := shutil.which(n)): return Path(p)
    raise FileNotFoundError('chrome not found on PATH')

# %% ../nbs/02_setup.ipynb #33c775b5
_PLIST = """<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0"><dict>
  <key>CFBundleName</key><string>{name}</string>
  <key>CFBundleDisplayName</key><string>{name}</string>
  <key>CFBundleIdentifier</key><string>ai.answer.fastcdp.{ident}</string>
  <key>CFBundleExecutable</key><string>launch</string>
  <key>CFBundleIconFile</key><string>icon</string>
  <key>CFBundlePackageType</key><string>APPL</string>
  <key>CFBundleVersion</key><string>1.0</string>
</dict></plist>
"""

def _ident(name): return re.sub(r'\W+', '-', name.lower()).strip('-')

def _mac_app(chrome, name, port, profile, dest):
    app = dest/f'{name}.app'
    (app/'Contents/MacOS').mkdir(parents=True, exist_ok=True)
    (app/'Contents/Resources').mkdir(parents=True, exist_ok=True)
    (app/'Contents/Info.plist').write_text(_PLIST.format(name=name, ident=_ident(name)))
    scr = app/'Contents/MacOS/launch'
    # `arch -arm64`: a script-bundle executable runs under Rosetta, and Chrome would inherit its x86_64 slice
    scr.write_text(f'#!/bin/sh\nexec arch -arm64 "{chrome}" --remote-debugging-port={port} --user-data-dir="{profile}" --no-first-run --no-default-browser-check "$@"\n')
    scr.chmod(0o755)
    shutil.copy(files('fastcdp')/'icons/cdp-chrome.icns', app/'Contents/Resources/icon.icns')
    return app

# %% ../nbs/02_setup.ipynb #0e47f9c1
def _linux_app(chrome, name, port, profile, dest):
    ic = dest/'icons/hicolor/256x256/apps/cdp-chrome.png'
    ic.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy(files('fastcdp')/'icons/cdp-chrome.png', ic)
    desk = dest/'applications'/f'{_ident(name)}.desktop'
    desk.parent.mkdir(parents=True, exist_ok=True)
    desk.write_text(f'''[Desktop Entry]
Type=Application
Name={name}
Exec="{chrome}" --remote-debugging-port={port} --user-data-dir="{profile}" --no-first-run --no-default-browser-check
Icon=cdp-chrome
Terminal=false
Categories=Development;
''')
    return desk

# %% ../nbs/02_setup.ipynb #e152d58b
def _win_app(chrome, name, port, profile, dest):
    ic = Path(profile)/'cdp-chrome.ico'
    ic.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy(files('fastcdp')/'icons/cdp-chrome.ico', ic)
    dest.mkdir(parents=True, exist_ok=True)
    lnk = dest/f'{name}.lnk'
    ps = f'''$s = (New-Object -ComObject WScript.Shell).CreateShortcut('{lnk}')
$s.TargetPath = '{chrome}'
$s.Arguments = '--remote-debugging-port={port} --user-data-dir="{profile}" --no-first-run --no-default-browser-check'
$s.IconLocation = '{ic}'
$s.Save()'''
    subprocess.run(['powershell', '-NoProfile', '-Command', ps], check=True)
    return lnk

# %% ../nbs/02_setup.ipynb #041b4876
@call_parse
def main(
    port:int=9223, # Debug port (`CDP.remote`'s default; 9222 would clash with the everyday browser's built-in debugging)
    profile:str=None, # Chrome profile dir (default: `~/.cache/fastcdp/cdp-chrome`)
    name:str='CDP Chrome' # Launcher name
):
    "Create an OS launcher for a debug-enabled Chrome with its own profile, ready for `CDP.remote`"
    profile = Path(profile) if profile else Path.home()/'.cache/fastcdp/cdp-chrome'
    chrome, sys = chrome_path(), platform.system()
    if sys == 'Darwin': res = _mac_app(chrome, name, port, profile, Path.home()/'Applications')
    elif sys == 'Linux': res = _linux_app(chrome, name, port, profile, Path.home()/'.local/share')
    elif sys == 'Windows': res = _win_app(chrome, name, port, profile, Path(os.environ['APPDATA'])/'Microsoft/Windows/Start Menu/Programs')
    else: raise RuntimeError(f'Unsupported OS: {sys}')
    print(f'Created {res}\nConnect with: cdp = await CDP.remote({port})')
    return res
